### ISSUE TITLE
Feature request: Configurable buttons

### ISSUE THREAD

**Issue by mahtDFR** [nornagon/saxi#89] opened 2021-06-27 20:13 UTC
If running on a Pi it would be good to have a button for 'shutdown' so I can control everything completely from the WebUI.
I have Saxi running on my Pi at boot, but to gracefully shutdown I need to issue a shutdown command via ssh.

**Comment by nornagon** [comment] 2021-06-28 17:06
Duplicate of #68

**Closed by nornagon** 2021-06-28 17:06 UTC
