### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by kevin227227** [nornagon/saxi#83] opened 2021-04-23 14:46 UTC
Can anyone give me instructions on how to install saxi on windows 10 ?

**Comment by nornagon** [comment] 2021-04-27 17:50
Duplicate of #81

**Comment by nornagon** [comment] 2021-04-27 17:50
Hi there, please don't open new issues when existing ones are closed. Instead, continue conversation on the original issue.

Thanks!

**Closed by nornagon** 2021-04-27 17:50 UTC

**Comment by kevin227227** [comment] 2021-04-29 03:47
hello, sorry, I thought that as it said "closed topic" no one was answering it, I am new and did not know, sorry.
